### ISSUE TITLE
tarsnapper doesn't launch with cron

### ISSUE THREAD

**Issue by e-founders** [miracle2k/tarsnapper#18]
When adding tarsnapper into a cronjob, it generates an error, I think it's due to a path problem (cron have a limited env):

Am I the only one who use tarsnapper with cron?

``` javascript
   Creating backup images: /images-20141113-104001
   Traceback (most recent call last):
  File "/usr/local/bin/tarsnapper", line 9, in <module>
    load_entry_point('tarsnapper==0.2.1', 'console_scripts', 'tarsnapper')()
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.2.1-py2.7.egg/tarsnapper/script.py", line 498, in run
    sys.exit(main(sys.argv[1:]) or 0)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.2.1-py2.7.egg/tarsnapper/script.py", line 491, in main
    command.run(job)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.2.1-py2.7.egg/tarsnapper/script.py", line 347, in run
    self.backend.make(job)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.2.1-py2.7.egg/tarsnapper/script.py", line 182, in make
    self.call(*args)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.2.1-py2.7.egg/tarsnapper/script.py", line 59, in call
    return self._exec_tarsnap(call_with)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.2.1-py2.7.egg/tarsnapper/script.py", line 64, in _exec_tarsnap
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by d5ve** [comment]
I had a similar issue, even with the crontab holding the full path to **tarsnapper**. I think it was due to **tarsnap** itself not being in $PATH. Setting PATH=$PATH:/usr/local/bin fixes this case as well.
