### ISSUE TITLE
Incompatible with Python 3

### ISSUE THREAD

**Issue by alanorth** [miracle2k/tarsnapper#36]
I tried to use tarsnapper with Python 3.5.0 and 3.4.3 and I get this error during `pip install` in a virtualenv:

```
$ pip install tarsnapper
Collecting tarsnapper
  Using cached tarsnapper-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/9j/vyqph8z14g72ftq41_wlndjh0000gn/T/pip-build-fzuxjgi6/tarsnapper/setup.py", line 28
        exec "version = %s" % match.group(1)
                          ^
    SyntaxError: invalid syntax
```

I will use Python 2.7.10 for now.

**Comment by miracle2k** [comment]
Python 3 should now be supported.

**Comment by alanorth** [comment]
Great, I just tested it and it's working with Python 3.6.0. Cheers!
