### ISSUE TITLE
set error exit status when backup not done

### ISSUE THREAD

**Issue by rbauduin** [miracle2k/tarsnapper#39]
When a source does not exist, tarsnapper doesn't do the backup:
`Not backing up 'mybackup', because not all given sources exist`
but 
```
echo $?
0
```

**Comment by miracle2k** [comment]
I think that change would make sense.

**Comment by jefft** [comment]
Likewise, if the tarsnap cachedir is corrupt, then `tarsnapper make` returns a 0 exit code despite no backup being made.

To demonstrate, delete `/var/cache/tarsnap` or wherever `cachedir` points to in tarsnap.conf, and run `tarsnapper -v make`:

```
+ /opt/atl_manage/venv/bin/tarsnapper -o configfile /etc/backups/tarsnap.conf -o v -c /etc/backups/tarsnapper.conf -v make
Creating backup jira: jira-20211228-110450
Executing: tarsnap --configfile /etc/backups/tarsnap.conf -v -c -f jira-20211228-110450 /var/atlassian/application-data/jira/backups/hourly.0
tarsnap: Sequence number mismatch: Run --fsck^M
tarsnap: Error creating new archive^M
tarsnap: Error exit delayed from previous errors.^M
Something went wrong with backup job: 'jira'
Traceback (most recent call last):
  File "/opt/atl_manage/venv/lib/python3.8/site-packages/tarsnapper/script.py", line 391, in run
    self.backend.make(job)
  File "/opt/atl_manage/venv/lib/python3.8/site-packages/tarsnapper/script.py", line 236, in make
    self.call(*args)
  File "/opt/atl_manage/venv/lib/python3.8/site-packages/tarsnapper/script.py", line 68, in call
    return self._exec_tarsnap(call_with)
  File "/opt/atl_manage/venv/lib/python3.8/site-packages/tarsnapper/script.py", line 88, in _exec_tarsnap
    raise TarsnapError("tarsnap failed with status {0}:{1}{2}".format(
tarsnapper.script.TarsnapError: tarsnap failed with status 1:
tarsnap: Sequence number mismatch: Run --fsck^M
tarsnap: Error creating new archive^M
tarsnap: Error exit delayed from previous errors.^M

Executing: tarsnap --configfile /etc/backups/tarsnap.conf -v --list-archives
jira-20210715-020102    2021-07-15 12:01:02^M
....
19 backups are matching
0 of those can be deleted
Keeping jira-20210715-020102
```
