### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by ecopoesis** [miracle2k/tarsnapper#41]
running `tarsnapper --target "\$date-03-HOURLY-tripoli-/home/backups/media/Pictures" --deltas 1d 7d 30d 360d 18000d - expire --dry-run` I get the following error:

```
Exception AttributeError: "'spawn' object has no attribute 'closed'" in <bound method spawn.__del__ of <pexpect.spawn object at 0x7fb18b286210>> ignored
Traceback (most recent call last):
  File "/usr/local/bin/tarsnapper", line 9, in <module>
    load_entry_point('tarsnapper==0.4.0', 'console_scripts', 'tarsnapper')()
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 546, in run
    sys.exit(main(sys.argv[1:]) or 0)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 536, in main
    command.run(job)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 314, in run
    self.expire(job)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 311, in expire
    self.backend.expire(job)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 179, in expire
    backups = self.get_backups(job)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 143, in get_backups
    for backup_path in self.get_archives():
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 118, in get_archives
    response = StringIO(self.call('--list-archives'))
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 65, in call
    return self._exec_tarsnap(call_with)
  File "/usr/local/lib/python2.7/dist-packages/tarsnapper-0.4.0-py2.7.egg/tarsnapper/script.py", line 72, in _exec_tarsnap
    encoding='utf-8')
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

I'm using Python 2.7.6.

**Comment by miracle2k** [comment]
It seems that the recently added Python 3 support is a bit broken; you can use an older version. 

If someone could contribute fixes in this regard, I would appreciate it.
