### ISSUE TITLE
tarsnapper fails with UnicodeDecodeError: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by fho** [miracle2k/tarsnapper#50]
one of my tarsnapper jobs always fails with the following error:
```
tarsnap: Removing leading '/' from member names
Something went wrong with backup job: 'crypt'
Traceback (most recent call last):
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/tarsnapper/script.py", line 381, in run
    self.backend.make(job)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/tarsnapper/script.py", line 223, in make
    self.call(*args)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/tarsnapper/script.py", line 65, in call
    return self._exec_tarsnap(call_with)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/tarsnapper/script.py", line 78, in _exec_tarsnap
    has_prompt = (child.expect([u'Please enter passphrase for keyfile .*?:', pexpect.EOF]) == 0)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/site-packages/pexpect/spawnbase.py", line 178, in read_nonblocking
    s = self._decoder.decode(s, final=False)
  File "/home/fho/apps/tarsnapper/ENV/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 47: invalid start byte
```
I'm using the following application versions:
```
(ENV) [fho@zerozero tarsnapper]$ python --version
Python 2.7.15
(ENV) [fho@zerozero tarsnapper]$ pip list
Package         Version
--------------- -------
pexpect         4.6.0  
pip             18.0   
ptyprocess      0.6.0  
python-dateutil 2.7.3  
PyYAML          3.13   
setuptools      40.0.0 
six             1.11.0 
tarsnapper      0.4.0  
wheel           0.31.1 
```

Update: For the job the problem occurs, also the following tarsnap message is logged:
`Can't translate pathname 'crypt/home-fho/Documents/Bilder/travemünde 7.7.07/DSC00513.JPG' to UTF-8` (http://mail.tarsnap.com/tarsnap-users/msg00447.html)
This might be the cause of the encoding error in tarsnapper.

**Comment by fho** [comment]
I had some files with cp1252 encoded filenames. I converted them with `convmv` to utf-8, that fixed the encoding problem with tarsnapper.

It would be good if tarsnapper would be able to handle this case (like tarsnap does).

**Comment by jefft** [comment]
Yes, this is caused by files with unencodable names. This command creates such a file:

````
touch "$(echo -n -e 'Growth Goals \x96 How to\x85.docx')"
````
