### ISSUE TITLE
dateutil.parser._parser.ParserError: Unknown string format

### ISSUE THREAD

**Issue by iphoting** [miracle2k/tarsnapper#65]
Hi,

It looks like tarsnapper breaks when the job name has more than one `-`:

```
$ /usr/local/bin/tarsnapper -c /opt/tarsnap/etc/tarsnapper.conf list
```

Error snippet:
```
Ignoring '/xxx/snipe-it-db-20210121-222959': Unknown string format: db-20210121-222959
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tarsnapper/script.py", line 155, in get_backups
    date = parse_date(match.groupdict()['date'], job.dateformat)
  File "/usr/local/lib/python3.7/dist-packages/tarsnapper/script.py", line 254, in parse_date
    return dateutil.parser.parse(string)
  File "/usr/local/lib/python3.7/dist-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: db-20210121-222959
```

Config snippet:
```  
snipe-it-db:
    sources:
      - /opt/snipe-it/sql-backup-archives
    target: /xxx/snipe-it-db-$date
```

**Comment by maratsh** [comment]
I have same issue. Could be that python version compatibility issue ? I'm using python 3.9
